name: SmartBear Supported Pull Request Comment Created

# Scenario: Once the code author commits all changes to branch, and PR updated, 
# they can comment with "/done"

# Example of trigger for this workflow:
#
# on:
#   issue_comment:                                     
#     types: [created]

on:
  workflow_call:  
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/done') }}
    name: Transition Jira Ticket to In Review
    steps:
    - name: login
      uses: atlassian/gajira-login@ca13f8850ea309cf44a6e4e0c49d9aa48ac3ca4c # v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - run: echo ${{ github.event.issue.title }}

    - name: Find Issue
      id: find
      uses: atlassian/gajira-find-issue-key@7d9cbdfce900a0fcf608050ce728620a928be8b6 # v3
      with:
        string: ${{ github.event.issue.title }}

    - run: echo "${{ steps.find.outputs.issue }}"

    - name: Transition issue
      if: steps.find.outputs.issue != ''
      uses: atlassian/gajira-transition@4749176faf14633954d72af7a44d7f2af01cc92b # v3
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "In Progress"