name: SmartBear Supported Issue Closed

# Example of trigger for this workflow:
#
# on:
#   issues:
#     types:
#       - closed

on:
  workflow_call:

jobs:
  if_closed:
    runs-on: ubuntu-latest
    name: Transition Jira ticket to Close
    steps:
    - name: login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.SMARTBEAR_JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.SMARTBEAR_JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.SMARTBEAR_JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.1.0
      with:
        jql: 'summary ~ "${{ github.event.repository.name }}#${{ github.event.issue.number }}:" AND project=${{ vars.SMARTBEAR_JIRA_PROJECT }}'

    - name: Log
      run: echo "Found issue ${{ steps.search.outputs.issue }}"

    - name: Transition issue
      if: steps.search.outputs.issue != ''
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "Done"