name: SmartBear Supported Branch Created

# Example of trigger for this workflow:
#
# on:
#   create:
#     branches:
#       - 'feature/**'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Transition Jira ticket to In Progress
    steps:
    - name: login
      uses: atlassian/gajira-login@ca13f8850ea309cf44a6e4e0c49d9aa48ac3ca4c # v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue
      id: find
      uses: atlassian/gajira-find-issue-key@7d9cbdfce900a0fcf608050ce728620a928be8b6 # v3
      with:
        from: branch

    - run: echo "${{ steps.find.outputs.issue }}"

    - name: Transition issue
      if: steps.find.outputs.issue != ''
      uses: atlassian/gajira-transition@4749176faf14633954d72af7a44d7f2af01cc92b # v3
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "In Progress"
